void() S_Precache =
{
    // sounds
    precache_sound("items/r_item1.wav");
    precache_sound("items/r_item2.wav");
    precache_sound("items/protect.wav");
    precache_sound("items/damage.wav");

    // models
    precache_model("progs/zom_gib.mdl");
    precache_model("progs/items/rogue/mervup_75.mdl");
    precache_model("progs/items/quoth/cross.mdl");
    precache_model("progs/invul.mdl");
    precache_model("progs/quaddama.mdl");
}